"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import constants

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "resources/rprdigi.icns",
    "resources": [
        "resources/icons",
        "resources/rprdigi.ico",
        "resources/MarkerMatic-Bridge.bwextension",
    ],
    "includes": ["mido.backends.portmidi"],
    "dylib_excludes": [
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tcl.framework",
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tk.framework",
    ],
    "plist": {
        "CFBundleIdentifier": constants.BUNDLE_IDENTIFIER,
        "CFBundleName": constants.APPLICATION_NAME,
        "CFBundleDisplayName": constants.APPLICATION_NAME,
        "NSHumanReadableCopyright": constants.APPLICATION_COPYRIGHT,
        "CFBundleShortVersionString": constants.VERSION,
        "CFBundleVersion": constants.VERSION,
        "NSRequiresAquaSystemAppearance": False,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
