"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "resources/rprdigi.icns",
    "resources": [
        "resources/icons",
        "resources/rprdigi.ico",
        "resources/MarkerMatic-Bridge.bwextension",
    ],
    "includes": ["mido.backends.portmidi"],
    "dylib_excludes": [
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tcl.framework",
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tk.framework",
    ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
